/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author angelynz95
 */
public class GenerateReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form GenerateReportPanel
     */
    public GenerateReportPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filePathTextField = new javax.swing.JTextField();
        filePathButton = new javax.swing.JButton();
        reportNameTextField = new javax.swing.JTextField();
        reportNameLabel = new javax.swing.JLabel();
        generateReportButton = new javax.swing.JButton();

        filePathTextField.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        filePathButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        filePathButton.setText("Pilih Lokasi Laporan");
        filePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathButtonActionPerformed(evt);
            }
        });

        reportNameTextField.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        reportNameLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        reportNameLabel.setText("Nama Laporan");

        generateReportButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        generateReportButton.setText("Buat Laporan");
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportNameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(filePathTextField))
                .addGap(18, 18, 18)
                .addComponent(filePathButton)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(generateReportButton)
                .addContainerGap(547, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportNameLabel)
                    .addComponent(reportNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filePathButton))
                .addGap(68, 68, 68)
                .addComponent(generateReportButton)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathButtonActionPerformed

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateReportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filePathButton;
    private javax.swing.JTextField filePathTextField;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JLabel reportNameLabel;
    private javax.swing.JTextField reportNameTextField;
    // End of variables declaration//GEN-END:variables
}
